#region BSD License
/*
 * Original BSD 3-Clause License (https://github.com/ComponentFactory/Krypton/blob/master/LICENSE)
 *  © Component Factory Pty Ltd, 2006 - 2016, (Version 4.5.0.0) All rights reserved.
 *
 *  New BSD 3-Clause License (https://github.com/Krypton-Suite/Standard-Toolkit/blob/master/LICENSE)
 *  Modifications by Peter Wagner (aka Wagnerp), Simon Coghlan (aka Smurf-IV), Giduac, Ahmed Abdelhameed, tobitege et al. 2017 - 2025. All rights reserved.
 */
#endregion

namespace PaletteDesigner;

public partial class ExportBaseSchemeClass : KryptonForm
{
    private readonly KryptonCustomPaletteBase _palette;
    private readonly SettingsManager _settingsManager;

    public ExportBaseSchemeClass(KryptonCustomPaletteBase palette, string defaultClassName, SettingsManager settingsManager)
    {
        _palette = palette ?? throw new ArgumentNullException(nameof(palette));
        _settingsManager = settingsManager ?? throw new ArgumentNullException(nameof(settingsManager));
        InitializeComponent();
        txtClassName!.Text = defaultClassName;
        txtFileName!.Text = defaultClassName + ".cs";
        txtFolder!.Text = _settingsManager.GetExportClassFolder();

        Load += ExportBaseSchemeClass_Load;
    }

    private void ExportBaseSchemeClass_Load(object? sender, EventArgs e)
    {
        if (Owner?.Icon != null)
        {
            Icon = Owner.Icon;
        }
    }

    private void BtnBrowse_Click(object? sender, EventArgs e)
    {
        using var dlg = new KryptonFolderBrowserDialog();
        if (dlg.ShowDialog(this) == DialogResult.OK)
        {
            txtFolder!.Text = dlg.SelectedPath;
        }
    }

    private void BtnCancel_Click(object? sender, EventArgs e) => DialogResult = DialogResult.Cancel;

    private void BtnCreate_Click(object? sender, EventArgs e)
    {
        string className = Utilities.IdentifierUtilities.SanitizeIdentifier(txtClassName!.Text);
        if (string.IsNullOrWhiteSpace(className))
        {
            KryptonMessageBox.Show(this, "Invalid class name.");
            return;
        }

        string folder = txtFolder!.Text.Trim();
        if (folder.Length == 0)
        {
            KryptonMessageBox.Show(this, "Select target folder.");
            return;
        }

        try
        {
            Directory.CreateDirectory(folder);
        }
        catch (Exception ex)
        {
            KryptonMessageBox.Show(this, ex.Message);
            return;
        }

        // Determine filename from textbox, ensure it ends with .cs
        string fileNameInput = txtFileName!.Text.Trim();
        if (string.IsNullOrWhiteSpace(fileNameInput))
        {
            KryptonMessageBox.Show(this, "Provide a filename.");
            return;
        }

        if (!fileNameInput.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
        {
            fileNameInput += ".cs";
        }

        string path = Path.Combine(folder, fileNameInput);

        if (File.Exists(path))
        {
            var res = KryptonMessageBox.Show(this, $"{fileNameInput} already exists. Overwrite?", "Confirm Overwrite", KryptonMessageBoxButtons.YesNo, KryptonMessageBoxIcon.Question);
            if (res != DialogResult.Yes)
            {
                return;
            }
        }

        try
        {
            var code = GenerateSchemeClassCode(_palette, className);
            File.WriteAllText(path, code, Encoding.UTF8);
            _settingsManager.SetExportClassFolder(folder);
            _settingsManager.SaveSettings();
            KryptonMessageBox.Show(this, "Class exported to " + path);
            DialogResult = DialogResult.OK;
        }
        catch (Exception ex)
        {
            KryptonMessageBox.Show(this, ex.Message);
        }
    }

    private static string ToColorExpr(Color c) => c.IsEmpty
        ? "GlobalStaticValues.EMPTY_COLOR"
        : (c.A != 255 ? $"Color.FromArgb({c.A}, {c.R}, {c.G}, {c.B})" : $"Color.FromArgb({c.R}, {c.G}, {c.B})");

    private static string GenerateSchemeClassCode(KryptonCustomPaletteBase palette, string className)
    {
        var enumValues = (SchemeBaseColors[])Enum.GetValues(typeof(SchemeBaseColors));
        var sb = new StringBuilder();
        sb.AppendLine("#region BSD License");
        sb.AppendLine("/*");
        sb.AppendLine(" * Auto-generated by Palette Designer");
        sb.AppendLine(" */");
        sb.AppendLine("#endregion");
        sb.AppendLine();
        sb.AppendLine("using System.Drawing;");
        sb.AppendLine();
        sb.AppendLine("namespace Krypton.Toolkit;");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {className} : KryptonColorSchemeBase");
        sb.AppendLine("{");
        const int braceCol = 59;
        foreach (var val in enumValues)
        {
            Color col = GetSchemeColorSafe(palette, val);
            string expr = ToColorExpr(col);

            string line = "    public override Color " + val + " ";
            int pad = braceCol - line.Length;
            if (pad < 1) pad = 1;
            line += new string(' ', pad) + "{ get; set; } = " + expr + ";";
            sb.AppendLine(line);
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static Color GetSchemeColorSafe(KryptonCustomPaletteBase? palette, SchemeBaseColors val)
    {
        if (palette == null)
        {
            return GlobalStaticValues.EMPTY_COLOR;
        }

        var m = palette.GetType().GetMethod("GetSchemeColor", BindingFlags.Public | BindingFlags.Instance);
        if (m != null)
        {
            try
            {
                return (Color)m.Invoke(palette, new object[] { val })!;
            }
            catch { }
        }

        if (palette is KryptonCustomPaletteBase kcp && kcp.BasePalette != null)
        {
            var mb = kcp.BasePalette.GetType().GetMethod("GetSchemeColor", BindingFlags.Public | BindingFlags.Instance);
            if (mb != null)
            {
                try
                {
                    return (Color)mb.Invoke(kcp.BasePalette, new object[] { val })!;
                }
                catch { }
            }

            var schemeArr = kcp.BasePalette.GetType().GetMethod("GetSchemeColors", BindingFlags.NonPublic | BindingFlags.Instance)?.Invoke(kcp.BasePalette, null) as Color[];
            if (schemeArr != null && (int)val < schemeArr.Length)
            {
                return schemeArr[(int)val];
            }
        }

        var scheme = palette.GetType().GetMethod("GetSchemeColors", BindingFlags.NonPublic | BindingFlags.Instance)?.Invoke(palette, null) as Color[];
        if (scheme != null && (int)val < scheme.Length)
        {
            return scheme[(int)val];
        }

        return GlobalStaticValues.EMPTY_COLOR;
    }
}