<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net481;net8.0-windows</TargetFrameworks>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Resources\Krypton.ico</ApplicationIcon>
    <OutputPath>..\..\..\Binaries\Krypton Palette\$(Configuration)\</OutputPath>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Nullable>enable</Nullable>
    <RootNamespace>PaletteUpgradeTool</RootNamespace>
    <AssemblyName>Palette Upgrade Tool</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>preview</LangVersion>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <NeutralLanguage>en</NeutralLanguage>
    <DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
  </PropertyGroup>

  <Choose>
    <When Condition="'$(SolutionName.Endswith(`Nuget`))'">
      <ItemGroup>
        <PackageReference Include="Krypton.Toolkit" Version="85.24.10.288" />
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <ProjectReference Include="..\..\..\..\..\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Krypton.Toolkit 2022.csproj" />
      </ItemGroup>
    </Otherwise>
  </Choose>

  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PackageIcon>Krypton Icon 128 x 128.png</PackageIcon>
    <BaseOutputPath>Z:\GitHub\Krypton-Suite - V85\Theme-Palettes\Applications\Binaries\Krypton Palette</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>